version: '2'
services:
  zookeeper:
    image: jplock/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.8.2.0
    container_name: kafka
    hostname: kafka
    links: 
     - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "0.0.0.0"
      KAFKA_ADVERTISED_PORT: 60432
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
    ports:
     - "60432:60432"
  mongodb:
    container_name: customer-datastore
    image: mongo:3.2
    command: mongod --smallfiles
  consumer:
    container_name: customer-service
    build: customer/target
    image: customer
    depends_on: 
      - mongodb
    ports:
      - "56789:56789"
    links:
      - mongodb
      - kafka
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb/test
  web:
    container_name: example-service
    build: example/target
    image: example
    depends_on: 
      - mongodb
    ports:
      - "9999:9999"
    links:
      - mongodb
      - kafka
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb/test